name: draftmode_geofence
description: Geofence.
version: 1.0.0+1
publish_to: "none" # So it doesn't accidentally get published

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  draftmode_ui:
    path: ../ui
  flutter_local_notifications: ^19.5.0
flutter:
  generate: true
  uses-material-design: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.2
